# Generated by Django 2.1.8 on 2019-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190522_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_info1',
            field=models.IntegerField(default=0),
        ),
    ]
