# Generated by Django 2.1.8 on 2019-05-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190524_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_info1',
            field=models.BooleanField(default=0),
        ),
    ]
