# Generated by Django 2.1.8 on 2019-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190524_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_info2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_info3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_info4',
            field=models.IntegerField(default=0),
        ),
    ]
