# Generated by Django 2.2.1 on 2019-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target1', models.CharField(max_length=50)),
                ('target2', models.CharField(max_length=50)),
                ('target_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
